# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Enable Emacs keybindings
# Skip word forward
bindkey "^[[1;9C" forward-word
# Skip word backward
bindkey "^[[1;9D" backward-word

# Option + Backspace to delete the word before the cursor
bindkey "^[^?" backward-kill-word

# Option + D to delete the word after the cursor
bindkey "^[d" kill-word

# Command + Backspace to delete the entire line
bindkey "^a^k" kill-line


# PATH modifications
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$PATH:/opt/homebrew/opt/kotlin-language-server/bin"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="$PATH:/Applications/IntelliJ IDEA CE.app/Contents/MacOS"
alias idea='idea . > /dev/null 2>&1 &'
export PATH="$PATH:/Applications/Android Studio.app/Contents/MacOS"
alias studio='studio . > /dev/null 2>&1 &'

# Add Homebrew Ruby to PATH
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH=$PATH:~/Library/Android/sdk/platform-tools

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# Created by `pipx` on 2024-12-29 15:09:09
export PATH="$PATH:/Users/tusharpal/.local/bin"
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# history setup
HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify


bindkey "^[[A" history-search-backward
bindkey "^[[B" hisotry-search-forward

alias ls="eza --icons=always"
# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"
# ---- Zoxide (better cd) ----
eval "$(zoxide init zsh)"

alias cd="z"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="/opt/homebrew/opt/node@22/bin:$PATH"
